AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{ cookiecutter.project_name }}
  {{ cookiecutter.project_short_description }}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
{%- if cookiecutter.include_safe_deployment == "y" %}
    AutoPublishAlias: live # More info about Safe Deployments: https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst
    DeploymentPreference:
      Type: Linear10PercentEvery1Minute
      Alarms:
        # Rollback deployment if any of the following CloudWatch alarms breach 
        - !Ref LiveAliasErrorMetricGreaterThanZeroAlarm
{% endif %}

Resources:
  {{ cookiecutter.function_name }}:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: {{ cookiecutter.function_name|lower }}
      Handler: app.lambda_handler
      Runtime: python3.7
{%- if cookiecutter.include_xray == "y" %}
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
{% endif %}
{%- if cookiecutter.include_apigw == "y" %}
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{{ cookiecutter.function_name|lower }}/{any_argument+}
            Method: any
{% endif %}
      # Policies: # Example inline policy
      #     - Version: "2012-10-17"
      #     Statement:
      #         - Effect: "Allow"
      #         Action:
      #             - "ssm:GetParameter"
      #         Resource:
      #             - "*"
      # Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      #     Variables:
      #         PARAM1: VALUE
{% if cookiecutter.include_safe_deployment == "y" %}
  LiveAliasErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
{% set variable = testing %}
          Value: !Sub "{{ '${'cookiecutter.function_name'}' }}:live"
        - Name: FunctionName
          Value: !Ref {{ cookiecutter.function_name }}
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
      TreatMissingData: notBreaching
{%- endif %}
{% if cookiecutter.include_implicit_role_policy == "y"%}
  # Adds IAM Policy to Lambda function IAM Role that is generated implicitly
  {{ cookiecutter.function_name }}AdditionalPermission:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "ParameterStoreSample"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "ssm:GetParameters"
            Resource: "*"
      Roles:
        - !Ref {{ cookiecutter.function_name|lower }}Role # Sample policy to demonstrate Implicit IAM Role created with SAM
{%- endif %}

Outputs:
{% if cookiecutter.include_apigw == "y"%}
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  {{ cookiecutter.function_name }}ApiGatewayURL:
    Description: "API Gateway endpoint URL for Prod environment for FirstFunction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{{ cookiecutter.function_name|lower }}/argument"
{%- endif %}
{{ cookiecutter.function_name|lower }}:
    Description: "{{ cookiecutter.function_name|lower }} Lambda Function ARN"
    Value: !GetAtt {{ cookiecutter.function_name|lower }}.Arn
{% if cookiecutter.include_implicit_role_policy == "y"%}
{{ cookiecutter.function_name|lower }}IamRole:
    Description: "Implicit IAM Role created for {{ cookiecutter.function_name|lower }} function"
    Value: !GetAtt {{ cookiecutter.function_name|lower }}Role.Arn
{%- endif %}
