AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{ cookiecutter.project_name }}
    
  {{ cookiecutter.project_short_description }}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
{%- if cookiecutter.include_safe_deployment == "y" %}
    AutoPublishAlias: live # More info about Safe Deployments: https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst
    DeploymentPreference:
      Type: Linear10PercentEvery1Minute 
      Alarms:
        # Rollback deployment if any of the following CloudWatch alarms breach 
        - !Ref LiveAliasErrorMetricGreaterThanZeroAlarm
{% endif %}

Resources:

  FirstFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: first_function
      Handler: app.lambda_handler
      Runtime: python3.7
{%- if cookiecutter.include_xray == "y" %}
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
{% endif %}
{%- if cookiecutter.include_apigw == "y" %}
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /first/{any_argument+}
            Method: any
{% endif %}
      # Policies: # Example inline policy
      #     - Version: "2012-10-17"
      #     Statement:
      #         - Effect: "Allow"
      #         Action:
      #             - "ssm:GetParameter"
      #         Resource:
      #             - "*"
      # Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      #     Variables:
      #         PARAM1: VALUE

{% if cookiecutter.include_safe_deployment == "y" %}
  LiveAliasErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${FirstFunction}:live"
        - Name: FunctionName
          Value: !Ref FirstFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
      TreatMissingData: notBreaching
{%- endif %}

{% if cookiecutter.include_implicitrolepolicy == "y"%}
  # Adds IAM Policy to Lambda function IAM Role that is generated implicitly
  FirstFunctionAdditionalPermission:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "ParameterStoreSample"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "ssm:GetParameters"
            Resource: "*"
      Roles:
        - !Ref FirstFunctionRole # Sample policy to demonstrate Implicit IAM Role created with SAM
{%- endif %}

Outputs:
{% if cookiecutter.include_apigw == "y"%}
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FirstApiGatewayURL:
    Description: "API Gateway endpoint URL for Prod environment for FirstFunction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/first/argument"
{%- endif %}

  FirstFunction:
    Description: "FirstFunction Lambda Function ARN"
    Value: !GetAtt FirstFunction.Arn

{% if cookiecutter.include_implicitrolepolicy == "y"%}
  FirstFunctionIamRole:
    Description: "Implicit IAM Role created for FirstFunction function"
    Value: !GetAtt FirstFunctionRole.Arn
{%- endif %}
